---
title: "Sushi Go Party"
author: "Keiran Suchak"
date: "2024-02-28"
categories: [boardgames]
image: "https://cf.geekdo-images.com/2f9uTicUSXkdPp2Yks6zFw__itemrep/img/Y_jPOWbp6_2qOzymSNIC6SZo4TE=/fit-in/246x300/filters:strip_icc()/pic5885689.jpg"
description: "Pass sushi around a bigger table and take the best dishes. Save
room for dessert!"
---

## Theming: What's the point?

* In Sushi Go Party, we are dining at a sushi restaurant, eating a three course
  meal.
* For each course, we will be collecting pieces of sushi on our plates as their
  travel around on the conveyor belt, and gaining points for the sushi
  combinations that we accumulate.

## Setting up: How to get started?

1. Place game board.
2. Initial choices:
    1. Choose player pieces.
    2. Choose menu; place menu tiles on board.
3. Collect cards pertaining to the chosen menu:
    1. Shuffle desert cards and place them to the side (face-down).
    2. Shuffler all other menu cards and place them to the side (face-down).
4. Play 3 rounds. For each round, deal out the cards according to the tables
   below:

* Desserts to add to deck each round:

|         | **2-5 Players** | **6-8 Players** |
|---------|:-----------:|:-----------:|
| **Round 1** |      5      |      7      |
| **Round 2** |      3      |      5      |
| **Round 3** |      2      |      3      |

* Cards to deal to players:

| **Players** | **Cards** |
|:-------:|:-----:|
|   2-3   |   10  |
|   4-5   |   9   |
|   6-7   |   8   |
|    8    |   7   |

## Rounds and Turns

* **A turn**:
    * This consists of players placing one card from their hand in front of them face-down.
    * All players place these cards **simultaneously**.
    * When all players have placed their cards, all players simultaneously reveal
      their card and add it to their collection.
        * Group cards of the same colour/type together.
    * After each turn, players pass their hand to the player to their left.
* **A round**:
    * This consists of players playing cards in front of them until their hands are empty.
    * After each round:
        * Players score their collections (according to the process below;
        * All cards are collected (**except the played desserts**);
        * Extra desserts are added to the deck;
        * The deck is shuffled;
        * Cards are dealt for the next round.
* **A game** consists of 3 rounds.

## Scoring

* Scoring takes place at the end of each round.
* When scoring each round, **exclude dessert cards** and set them aside - these
  will be scored after all rounds have been completed.
* Add up the scores from the round based on the rules on the menu tiles.
* Players move their pieces around the scoring track accordingly.
* After scoring the third round, score the dessert cards.
* The person with the most points wins.
* If scores are tied, the player with the most dessert cards wins.

