project:
  type: website

website:
  title: "Keiran Suchak"
  navbar:
    right:
      - icon: github
        href: https://github.com/ksuchak1990/
    left:
      - cv.qmd
      - publications.qmd
      - blog.qmd
      - boardgames.qmd

format:
  html:
    theme: pulse
    toc: true
    includes:
      in_header: |
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400&family=Merriweather:wght@400&display=swap" rel="stylesheet">
    css: styles.css
    code-line-numbers: true
    code-block-bg: true


execute:
  freeze: auto
