project:
  type: website

website:
  title: "Keiran Suchak"
  navbar:
    right:
      - icon: github
        href: https://github.com/ksuchak1990/
    left:
      - cv.qmd
      - projects.qmd
      - publications.qmd
      - blog.qmd
      - boardgames.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

execute:
  freeze: auto
