---
title: "Micro Architects"
author: "Keiran Suchak"
date: 2024-03-03
categories: [micro]
image: "https://cf.geekdo-images.com/D5kaA15fzqwqgLEBoi_-mA__itemrep/img/RcmrRxeH31KWuVUi55i85OPpNQQ=/fit-in/246x300/filters:strip_icc()/pic7161499.jpg"
description: "Plan and build a sprawling MICRO metropolis!"
---

## Theming

## Setting up

1. Place the Architects board in the middle of the table.
2. Provide each player with the following:
  * 1 City board
  * A Scoring token (of the player's chosen colour)
  * 6 Action tokens (of the player's chosen colour)
3. Players place 2 of their Action tokens in their player area (i.e. near their
   City board), and place the remaining tokens aside.
4. Players place their Scoring tokens on the Architects board.
5. Place all buildings in the bag, shake well and draw the appropriate number,
   placing them in rows *below* the Architects board (see @tbl-players-buildings-rows-1).
6. Draw 6 additional buildings from the bag and place them in the Backup Plans
   section of the Architects board.
5. Place the following cards around the board:
  * **Goal cards:** Place 3 pairs of cards *above* the Architects board
  * **Service cards:** Place 3 cards *left* of the Architects board
  * **Requirement cards:** Place $x = l_{building} + l_{backup}$ cards *right* of the Architects board, where $l_{building}$ is the number of Landmarks in the first row of the Building Plans and $l_{backup}$ is the number of Landmarks in Backup Plans.
6. Place boats nearby in reach of all players.
7. The First Player card goes to the person who last held a hammer.

| **Number of Players** | **Number of Rows** | **Buildings per Row** |
|:---------------------:|:------------------:|:---------------------:|
|           2           |          2         |           10          |
|           3           |          3         |           9           |
|           4           |          4         |           8           |

: Table of number of rows of buildings based on number of players (Round 1). {#tbl-players-buildings-rows-1}

## Rounds

* A **Game** is divided into 3 rounds.
* A **Round** consists of 3 phases:
    1. Action phase
    2. Scoring phase
    3. Cleanup phase

### Phases

1. Action phase:
    i. Taking buildings
    ii. Performing actions:
        * Overhaul
        * Backup Plan
        * Relocation
        * Demanding Residents
    iii. Acquiring services
2. Scoring phase:
    i. Goals
    ii. Landmarks
    iii. Services
3. Cleanup phase:
    * If this is the end of Round 3, skip the Cleanup phase.
    * Flip both scored Goal cards face down. In the following round, your will
      score based on the next two Goal cards.
    * Put the buildings from the Backup Plans section back in the bag, shake
      well and draw 6 new Buildings to place in the Backup Plans section.
    * Draw new Buildings and place them below the Architects board according to
      the player count (see @tbl-players-buildings-rows-2 and
      @tbl-players-buildings-rows-3).
    * Discard the remaining Requirement tiles and replace them with as many new
      ones as there are Landmarks in the first row of the Building Plans and
      Backup Plans combined. If there are non, then no Requirement tiles are
      placed.
    * Each players receives 2 Action tokens.
    * Pass the First Player card to the left.

| **Number of players** | **Number of rows** | **Number of buildings per row** |
|:---------------------:|:------------------:|:-------------------------------:|
|             2         |            2       |                  8              |
|         3             |            3       |                  9              |
|         4             |            4       |                  12             |

: Table of number of rows of buildings based on number of players (Round 2). {#tbl-players-buildings-rows-2}

| **Number of players** | **Number of rows** | **Number of buildings per row** |
|:---------------------:|:------------------:|:-------------------------------:|
|             2         |            2       |                  10             |
|             3         |            3       |                  9              |
|             4         |            4       |                  8              |

: Table of number of rows of buildings based on number of players (Round 3). {#tbl-players-buildings-rows-3}

## Scoring

## Terminology

* **Landmarks:** Black buildings
* **Building Plans:** The rows of buildings placed below the Architects board
* **Overhaul:**
    * Swap two Buildings of your choice in your City.
    * If you are swapping a Landmark, you must also take one of the Requirement tiles beside that black and place it beside the new black.
* **Backup Plan:**
    * Swap a chosen Building from your City with one of the available ones in the Backup Plans section of the Architects board.
    * If you choose a Landmark from the Backup Plans section, your must also choose one of the available Requirements tiles and place it beside the black where your place the new Landmark.
    * If you swap a Landmark from your City with another Building from the Backup Plans section, remove any one of the Requirement tiles from that Landmark's block and put it back with the Landmark Requirements tiles next to the Architects board.
* **Relocation:**
    * Move a Building to any other available space in your City.
    * If this would result in filling a black with no Boat token beside it, draw one Boat token and place it on the Life Ring by that block.
* **Demanding Residents:**
    * Draw 2 additional Services cards and place them face up beside the others. 
    * You can now decide if you want to spend 2 Boat tokens and pick one of the available 5 Service cards.
    * If you pick one of the extra 2 Services cards, place the remaining one into the discard pile.
    * If you decide to take one of the basic 3 Service cards, refill the offer with a new card from the top of the Service deck and discard 2 previously drawn Service cards.
